
[build]
  command = "npm run build"
  publish = "public/"
  functions = "functions/"
 [[plugins]]
package = "@netlify/plugin-functions-install-core" 

[context.production]
  environment = { FAUNADB= "fnAD89jK7LACByaqsdWFqQRlVxuWKSPZUez8mLnY"}

